-- MySQL Script generated by MySQL Workbench
-- Mon Jul  9 18:02:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hidenseek
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hidenseek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hidenseek` DEFAULT CHARACTER SET utf8 ;
USE `hidenseek` ;

-- -----------------------------------------------------
-- Table `hidenseek`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hidenseek`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `distinct_id` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `permission` ENUM('LOW', 'HIGH', 'TOTAL') NOT NULL DEFAULT 'LOW',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `identifier_UNIQUE` (`distinct_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hidenseek`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hidenseek`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) UNIQUE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hidenseek`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hidenseek`.`local` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) UNIQUE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hidenseek`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hidenseek`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT NOW(),
  `admuser_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `local_id` INT NOT NULL,
  PRIMARY KEY (`id`, `admuser_id`, `category_id`, `local_id`),
  INDEX `fk_item_category1_idx` (`category_id` ASC),
  INDEX `fk_item_local1_idx` (`local_id` ASC),
  INDEX `fk_item_user1_idx` (`admuser_id` ASC),
  CONSTRAINT `fk_item_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `hidenseek`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_local1`
    FOREIGN KEY (`local_id`)
    REFERENCES `hidenseek`.`local` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_user1`
    FOREIGN KEY (`admuser_id`)
    REFERENCES `hidenseek`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hidenseek`.`claim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hidenseek`.`claim` (
  `user_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `argument` TEXT NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`user_id`, `item_id`),
  INDEX `fk_user_has_item_item1_idx` (`item_id` ASC),
  INDEX `fk_user_has_item_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_item_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `hidenseek`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `hidenseek`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hidenseek`.`evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hidenseek`.`evaluation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('APPROVED', 'NOT_APPROVED', 'NOT_EVALUATED') NOT NULL DEFAULT 'NOT_EVALUATED',
  `datetime` DATETIME NOT NULL DEFAULT NOW(),
  `claim_user_id` INT NOT NULL,
  `claim_item_id` INT NOT NULL,
  `admuser_id` INT NOT NULL,
  PRIMARY KEY (`id`, `claim_user_id`, `claim_item_id`, `admuser_id`),
  INDEX `fk_evaluation_claim1_idx` (`claim_user_id` ASC, `claim_item_id` ASC),
  INDEX `fk_evaluation_user1_idx` (`admuser_id` ASC),
  CONSTRAINT `fk_evaluation_claim1`
    FOREIGN KEY (`claim_user_id` , `claim_item_id`)
    REFERENCES `hidenseek`.`claim` (`user_id` , `item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluation_user1`
    FOREIGN KEY (`admuser_id`)
    REFERENCES `hidenseek`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
